### ISSUE TITLE
Due date for questions

### ISSUE THREAD

**Issue by sarahruggless** [18F/bpa-disaster-data-portal-pilot#1]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Question/Comment
The due date for questions is February 21st and the due date for the proposals is also February 21st. Can you please clarify?

**Comment by oghaffari** [comment]
Thanks for pointing this out. We have updated the GitHub document to reflect the correct dates from the official RFQ that was posted on eBuy.
