### ISSUE TITLE
GIS Platform 

### ISSUE THREAD

**Issue by aristorm** [18F/bpa-disaster-data-portal-pilot#10]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Aristo Mitchell, Techflow Proposal Manager 

## Section of RFQ documents
3.0 Scope - Page 2, paragraph 2,  

## Question/Comment
Does the government have a preferred GIS platform?

**Comment by randyhart** [comment]
No, there is no preferred platform. The resulting software must use only open source components and exchange GIS data using open standards.
