### ISSUE TITLE
User Identity Management

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-disaster-data-portal-pilot#11]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Jason McNutt, aBPA Manager, Applied Information Sciences

## Section of RFQ documents
PWS Section 5 Tasks

## Question/Comment
Does the government require the vendor to establish user identities and will the vendor be required to setup delegation into the FEMA API Services on behalf of those identities?  Does the government foresee integration with a HUD identity Management service or source?

**Comment by randyhart** [comment]
As to the first question, yes, this system requires a registration/validation component, with all attendant features of any user authentication system. It will require two-factor authentication (2FA). As to the second question, yes, this should integrate with HUD's identity management service. It must link with Siteminder (https://hudapps.hud.gov/login/login_wass_internal.fcc). The requisite technical assistance will be provided by the HUD team to the selected vendor.
