### ISSUE TITLE
Open Source 

### ISSUE THREAD

**Issue by aristorm** [18F/bpa-disaster-data-portal-pilot#12]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Aristo Mitchell, Techflow Proposal Manager 

## Section of RFQ documents
Request for Proposal, Page 4, Paragraph F, first sentence.

## Question/Comment
Must an Example submitted be fully Open Sourced to be compliant or is it allowable to be simply developed in Open Source frameworks? Further, If an Example project is allowed that is not Open Sourced, will it result in a lower evaluation rating?

It is common, as Federal schedule and contract holders, to have Examples developed in Open Source frameworks for Federal Government Clients, however, those clients typically have not Open Sourced the source code to these projects. Not allowing these examples may exclude highly relevant experiences from consideration.

**Comment by randyhart** [comment]
We prefer to be able to examine the code base, and a public repository makes this process simpler. We also have a strong preference for working in the open, and therefore experience with this is beneficial.
