### ISSUE TITLE
PII Data

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-disaster-data-portal-pilot#13]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Jason McNutt, aBPA Manager, Applied Information Sciences

## Section of RFQ documents
PWS Section 6.1.1 Skills and Knowledge

## Question/Comment
Will the vendor need to store Personally Identifiable Information (PII)?  And if so what policies will the vendor have to follow to accommodate the storage of PII?

**Comment by randyhart** [comment]
No, the vendor will not be required to store any Personally Identifiable Information (PII). However, the vendor will be required to work with and have access to PII. All FAR and GSAM sections mentioned in the RFQ will govern how that PII should be handled.
