### ISSUE TITLE
FEMA Security Requirements

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-disaster-data-portal-pilot#2]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFO documents
PWS, Page 1, Section 1.0 Objectives, 3rd paragraph

## Question/Comment
The PWS indicates that 'all items will be developed while keeping in mind general privacy act related requirements as well as the heightened security requirements imposed upon this project by FEMA.' Could the government elaborate on the FEMA heightened security requirements and their potential impact on the project?

**Comment by randyhart** [comment]
The data that will be transmitted by this tool are governed by a Computer Matching Agreement (CMA) between HUD and FEMA. That CMA stipulates the legal authority for the data exchange, and specifies the allowable uses of the data. The CMA is currently being revised, but the previously approved version is available at https://www.federalregister.gov/documents/2016/09/14/2016-22006/privacy-act-of-1974-notice-of-a-computer-matching-program-between-the-department-of-housing-and.
