### ISSUE TITLE
End Users of the Pilot

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-disaster-data-portal-pilot#3]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFO documents
PWS, Page 2, Section 3.0 Scope, 3rd paragraph

## Question/Comment
The PWS indicates that the contractor will work with 2-3 municipalities; is the intent that these 2-3 municipalities will be the only end users of this pilot once the project goes live ?

**Comment by randyhart** [comment]
The contractor will work with 2-3 municipalities for user research purposes. The end result will be a project that will support a larger user base. To get an idea of how many users there would be if the system were to go live today, please view the active disaster grants, here: https://www.hudexchange.info/programs/cdbg-dr/cdbg-dr-grantee-contact-information/#all-disasters.
