### ISSUE TITLE
Current Analytics Platform

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-disaster-data-portal-pilot#4]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFO documents
PWS, Page 4, Section 5.0 Tasks, 9th Bullet

## Question/Comment
Is there a current analytics platform that should be used for this project?

**Comment by randyhart** [comment]
No.
