### ISSUE TITLE
Secret Clearance Requirements

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-disaster-data-portal-pilot#5]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFQ documents
PWS, Page 6, Section 6.1.2.C Key Personnel, 7th bullet

## Question/Comment
The PWS indicates that a secret clearance is desired for the technical lead. Is it a requirement that contract staff hold an active secret, top secret, or TS-SCI clearance? If so, what roles must hold a clearance?

**Comment by randyhart** [comment]
The PWS is amended to delete the reference to a secret clearance. Please see PWS Amend002 attachment.
