### ISSUE TITLE
Current Host Environment

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-disaster-data-portal-pilot#6]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFQ documents
PWS, Page 4, Section 5.0 Tasks

## Question/Comment
Can the government confirm whether the host environment is already provisioned/in place? If so, is it cloud based or hosted in a government data center?

**Comment by randyhart** [comment]
The host environment will be cloud.gov.
