### ISSUE TITLE
Clarification on base + contingency

### ISSUE THREAD

**Issue by BlakeNewman** [18F/bpa-disaster-data-portal-pilot#8]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Blake Newman, Agileana

## Section of RFQ documents
001 RFQ - Paragraph 3 - Period of Performance

## Question/Comment
The RFI states that a contingency of 6 months could be exercised if required. Is that contingency in addition to the 4 months stated for a total of potentially 10 months?

**Comment by randyhart** [comment]
This is a contingency option period that the government does not intend to exercise unless there's a worst case scenario of having to wrap up loose ends. Offerors should assume that this contingency option will not be exercised.
