### ISSUE TITLE
FEMA APIs

### ISSUE THREAD

**Issue by jmmcnj** [18F/bpa-disaster-data-portal-pilot#9]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Jason McNutt, aBPA Manager, Applied Information Sciences

## Section of RFQ documents
PWS Section 5 Tasks

## Question/Comment
What FEMA APIs is the government referring to in Section 5 Tasks?  Are these part of the OpenFEMA API datasets?  Could the government provide a link or sample of the dataset(s)?

**Comment by randyhart** [comment]
This is not part of the OpenFEMA API datasets. You can review detailed information about the API by reviewing the attachments to the Computer Matching Agreement between HUD and FEMA, located here: https://www.federalregister.gov/documents/2016/09/14/2016-22006/privacy-act-of-1974-notice-of-a-computer-matching-program-between-the-department-of-housing-and.
